CREATE TABLE h_abroncs(
       id number,
       tulaj_id number,
       felni_id number,
       evszak varchar2(250) not null,
       betarolas_ideje date not null,
       gyarto varchar2(250) not null,
       meret number not null,
       profilarany number not null,
       atmero number not null,
       terheles_index number,
       sebesseg_index varchar2(2),
       profilmelyseg number,
       dotszam number,
       modosito_user varchar2(250),
       modositasi_ido timestamp(6),
       keszito_user varchar2(250),
       keszito_ido timestamp(6),
       dml_tipus char(1),
       sor_verzio number
       ) tablespace users;
